# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'MarvelApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelApp
    pod 'Alamofire', '~> 4.7'
    pod 'CryptoSwift', '~> 0.11.0'
    pod 'SDWebImage', '~> 4.0'



  target 'MarvelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
