# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Marvel Comics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Texture', '2.6'
  pod 'Alamofire', '4.6.0'
  pod 'CryptoSwift', '0.8.3'

  target 'Marvel ComicsTests' do
    inherit! :search_paths

    pod 'Mockingjay', '2.0.1'
    pod 'Nimble', '7.0.3'
  end
end
